
[tool.black]
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
line-length = 88

src_folder = "./."

[tool.coverage]
[tool.coverage.run]
omit = ["tests/*", "*conftest.py", "*/interfaces/*", "*/__init__.py"]
